CREATE TABLE EMPLEAT(
    N_SS NUMBER PRIMARY KEY,
    NOM VARCHAR2(50),
    LLINATGES VARCHAR2(50),
    EMAIL VARCHAR2(50),
    IBAN VARCHAR2(40)
);

CREATE TABLE PLAÇA(
    CODI NUMBER PRIMARY KEY,
    NOM_TIPUS_PLAÇA VARCHAR2(50),
    ID_SUPERVISOR NUMBER,
    FOREIGN KEY (ID_SUPERVISOR) REFERENCES PLAÇA (CODI)
    
);

CREATE TABLE TIPUS_PLAÇA(
    NOM_TIPUS_PLAÇA VARCHAR2(50) PRIMARY KEY,
    NOM VARCHAR2(50),
    FUNCIÓ_TIPUS_PLAÇA VARCHAR2(50),
    SALARI NUMBER,
    FOREIGN KEY (NOM_TIPUS_PLAÇA) REFERENCES PLAÇA (CODI)
);

CREATE TABLE NOMINA(
    ID NUMBER PRIMARY KEY,
    IMPORT NUMBER,
    IBAN_PAGAMENT VARCHAR2(40),
    N_SS_EMPLEAT NUMBER,
    CODI_PLAÇA NUMBER,
    FOREIGN KEY (N_SS_EMPLEAT) REFERENCES EMPLEAT (N_SS),
    FOREIGN KEY (CODI_PLAÇA) REFERENCES PLAÇA (CODI)
);

CREATE TABLE OCUPABILITAT(
    N_SS_EMPLEAT NUMBER,
    CODI_PLAÇA NUMBER,
    DATA_INICI DATE,
    DATA_FI DATE,
    PRIMARY KEY (N_SS_EMPLEAT, CODI_PLAÇA),
    FOREIGN KEY (N_SS_EMPLEAT) REFERENCES EMPLEAT (N_SS),
    FOREIGN KEY (CODI_PLAÇA) REFERENCES PLAÇA (CODI)
);