--EJERCICIO 1

CREATE TABLE PRODUCTE (
  	NOM VARCHAR2(20) PRIMARY KEY,
    PREU_UNITARI NUMBER(10) NOT NULL
);

CREATE TABLE MINORISTA(
    CIF VARCHAR2(9) PRIMARY KEY CHECK(LENGTH(CIF) = 9),
    NOM VARCHAR2(20) NOT NULL
);

CREATE TABLE COMANDA(
    CODI NUMBER PRIMARY KEY,
    PREU_TOTAL NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    QUANTITAT NUMBER NOT NULL,
    CIF_MINORISTA VARCHAR2(9) NOT NULL,
    NOM_PRODUCTE VARCHAR2(20),
    FOREIGN KEY (CIF_MINORISTA) REFERENCES MINORISTA(CIF),
    FOREIGN KEY (NOM_PRODUCTE) REFERENCES PRODUCTE(NOM)
);

CREATE TABLE REPARTIDOR(
  	NUM_SS NUMBER PRIMARY KEY,
    NOM VARCHAR2(20) NOT NULL
);

CREATE TABLE INTENT_ENTREGA(
    CODI NUMBER PRIMARY KEY,
	FECHA DATE NOT NULL UNIQUE,
    ESTAT VARCHAR2(100) NOT NULL UNIQUE,
    CODI_REPROGRAMAT NUMBER,
    CODI_COMANDA NUMBER,
    NUM_SS_REPARTIDOR NUMBER,
    FOREIGN KEY (CODI_REPROGRAMAT) REFERENCES INTENT_ENTREGA(CODI),
    FOREIGN KEY (CODI_COMANDA) REFERENCES COMANDA (CODI),
    FOREIGN KEY (NUM_SS_REPARTIDOR) REFERENCES REPARTIDOR (NUM_SS)

);

--EJERCICIO 2

INSERT INTO MINORISTA(CIF,NOM) VALUES('AB2323678','Hector');
INSERT INTO MINORISTA(CIF,NOM) VALUES('A56904732','Toni');
INSERT INTO PRODUCTE(NOM,PREU_UNITARI) VALUES('Mando a distancia', 10);
INSERT INTO PRODUCTE(NOM,PREU_UNITARI) VALUES('Sudadera', 20);
INSERT INTO REPARTIDOR(NUM_SS,NOM) VALUES(103938030983, 'Jose');
INSERT INTO COMANDA(CODI, PREU_TOTAL, FECHA, QUANTITAT, CIF_MINORISTA, NOM_PRODUCTE) VALUES(1234, 15, TO_DATE('01/12/2024', 'DD/MM/YYYY'), 1, 'AB2323678', 'Mando a distancia');
INSERT INTO COMANDA(CODI, PREU_TOTAL, FECHA, QUANTITAT, CIF_MINORISTA, NOM_PRODUCTE) VALUES(6734, 25, TO_DATE('09/02/2024', 'DD/MM/YYYY'), 2, 'A56904732', 'Sudadera');
INSERT INTO INTENT_ENTREGA(CODI,FECHA,ESTAT,CODI_COMANDA,NUM_SS_REPARTIDOR) VALUES (6666, TO_DATE('08/12/2024', 'DD/MM/YYYY'), 'COMPLETAT', 1234, 103938030983);
INSERT INTO INTENT_ENTREGA(CODI,FECHA,ESTAT,CODI_REPROGRAMAT,CODI_COMANDA,NUM_SS_REPARTIDOR) VALUES (8888, TO_DATE('15/02/2024', 'DD/MM/YYYY'), 'REPROGRAMAT', 8888, 6734, 103938030983);
INSERT INTO INTENT_ENTREGA(CODI,FECHA,ESTAT,CODI_COMANDA,NUM_SS_REPARTIDOR) VALUES (8888, TO_DATE('16/02/2024', 'DD/MM/YYYY'), 'COMPLETAT',  6734, 103938030983);

--EJERCICIO 3

ALTER TABLE PRODUCTE ADD DESCRIPCIO VARCHAR2(2000);
ALTER TABLE INTENT_ENTREGA MODIFY FECHA TIMESTAMP;
ALTER TABLE PRODUCTE DROP COLUMN PREU_UNITARI;
UPDATE MINORISTA SET NOM='MINORISTA DE PROVA' WHERE CIF='AB2323678';
DELETE INTENT_ENTREGA WHERE ESTAT='COMPLETAT';
TRUNCATE TABLE INTENT_ENTREGA;